version: "3"
services:
  db:
    image: "postgres:11"
    container_name: "pg_pofl"
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=pofl
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=pofl
volumes:
  pg_data:
